spring.datasource.url: jdbc:h2:mem:TOME;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: tome
spring.datasource.password:
spring.h2.console.enabled: true

spring.thymeleaf.cache: false
spring.thymeleaf.mode: HTML
