spring:
  datasource:
    driverClassName: org.h2.Driver
    #    url: jdbc:h2:./h2db/tomedb
    url: jdbc:h2:mem:TOME;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    username: tome
    password:
  h2:
    console:
      enabled: true
  thymeleaf:
    cache: false
    mode: HTML
