DROP TABLE IF EXISTS TIME_EVENT;
CREATE TABLE TIME_EVENT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    event_date_time DATETIME
);

DROP SEQUENCE IF EXISTS BOOK_MANAGEMENT_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS BOOK_MANAGEMENT_SEQUENCE START WITH 1 INCREMENT BY 1;

DROP TABLE IF EXISTS BOOK_MANAGEMENT;
CREATE TABLE IF NOT EXISTS BOOK_MANAGEMENT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    BOOK_ID VARCHAR(10) NOT NULL,
    GENRE VARCHAR(20) NOT NULL,
    TITLE VARCHAR(20) NOT NULL,
    AUTHOR VARCHAR(20) NOT NULL,
    CONTENTS VARCHAR(100) NOT NULL,
    VOLUME NUMBER NOT NULL,
    CREATE_DATE DATETIME
);
