DROP TABLE IF EXISTS TIME_EVENT;
CREATE TABLE TIME_EVENT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    event_date_time DATETIME
);

DROP TABLE IF EXISTS BOOK_MANAGEMENT;
CREATE TABLE BOOK_MANAGEMENT (
    id INT PRIMARY KEY AUTO_INCREMENT,
    GENRE VARCHAR(20) NOT NULL,
    TITLE VARCHAR(20) NOT NULL,
    AUTHOR VARCHAR(20) NOT NULL,
    CONTENTS VARCHAR(100) NOT NULL,
    VOLUME NUMBER NOT NULL,
    CREATE_DATE DATETIME
);
